language: java

env:
- TERM=dumb

before_install:

- wget http://dl.google.com/android/adt/adt-bundle-linux-x86_64-20131030.zip
- unzip adt-bundle-linux-x86_64-20131030.zip
- export ANDROID_HOME=$PWD/adt-bundle-linux-x86_64-20131030/sdk
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools


# use Gradle 1.7 
- wget http://services.gradle.org/distributions/gradle-1.7-bin.zip
- unzip gradle-1.7-bin.zip
- export GRADLE_HOME=$PWD/gradle-1.7
- export PATH=$GRADLE_HOME/bin:$PATH

after_success:
- mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:cobertura

